### ISSUE TITLE
User registration link for already registered user is not handled properly

### ISSUE THREAD

**Issue by Milstein** [nerc-project/regapp#20]
This direct server to `500 error` with following debug trace:

```
KjG5-JxR8af3yBtHD72aFCqKEzEN79uggorYlyQ'}
2022-08-04 12:12:58,014 django.request       ERROR     Internal Server Error: /registration/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/code/regapp/apps/regapp/views/registration.py", line 89, in registration
    existing_mss_account_info = mss_userinfo_result[0]
KeyError: 0
```
This should be handled with using this function: https://github.com/nerc-project/regapp/blob/main/apps/regapp/views/registration.py#L101-L108

**Comment by knikolla** [comment]
The description and title of this issue is incorrect.

That `KeyError` is not being hit because there already exists a user. `KeyError` is being hit because the API call is returning an error in JSON dict format. Since `mss_userinfo_result` is a dictionary and `len` of a non-empty dictionary is `> 1`, the check is passing, and then fails at attempting to open element `[0]` of the dictionary, rather than the first element of the array.

I believe what is happening is that RegApp is getting a `401 Unauthorized` and failing to parse it.

**Comment by culbert** [comment]
error is on line 89, suggested fix is after exception gets thrown
issue is likely that json is error message/dict and not an array
API doc says that json always produced (and requests exceptions are caught) so, likely solution is to check status code. other option is to try to detect array but that is ugly at best

On Thu, 2022-08-04 at 09:52 -0700, Milstein Munakami wrote:

This direct server to 500 error with following debug trace:

KjG5-JxR8af3yBtHD72aFCqKEzEN79uggorYlyQ'}
2022-08-04 12:12:58,014 django.request       ERROR     Internal Server Error: /registration/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/code/regapp/apps/regapp/views/registration.py", line 89, in registration
    existing_mss_account_info = mss_userinfo_result[0]
KeyError: 0


This should be handled with using this function: https://github.com/nerc-project/regapp/blob/main/apps/regapp/views/registration.py#L101-L108

**Comment by knikolla** [comment]
Fixed by https://github.com/nerc-project/mss-keycloak/pull/16
